# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.daemon=true

# Forge Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

# Mod Properties
mod_id=faktocraft
mod_name=Faktocraft
mod_license=MIT
mod_version=0.0.6
mod_group_id=com.faktocraft
mod_authors=pedrocmota
mod_description=A modern port of IndustrialCraft 2, Tech Reborn, BuildCraft and Logistics Pipes, brought together into a single mod: electrical machines, power grids, item and fluid pipes, and logistics.

rei_version=12.1.785
architectury_version=9.2.14
wthit_version=8.21.1
jei_version=15.20.0.106
jade_version=11.13.3+forge
cloth_config_version=11.1.136
badpackets_version=0.4.3
embeddium_version=0.3.31+mc1.20.1
distant_horizons_version=3.2.0-b-1.20.1
oculus_version=1.20.1-1.8.0
