package com.faktocraft.gametest;

final class GameTestIndex {

  private GameTestIndex() {
  }

  static final String[][] TESTS = {
      { "com.faktocraft.gametest.fluids.AcidDamageGameTest",
          "acidHurtsOnContact",
          "aciddamagegametest.acidhurtsoncontact", "static" },
      { "com.faktocraft.gametest.fluids.AcidDamageGameTest",
          "acidHurtsStandingPlayerOnContact",
          "aciddamagegametest.acidhurtsstandingplayeroncontact", "static" },
      { "com.faktocraft.gametest.fluids.AcidDamageGameTest",
          "acidHurtsWalkingPlayerOnContact",
          "aciddamagegametest.acidhurtswalkingplayeroncontact", "static" },
      { "com.faktocraft.gametest.fluids.AcidDamageGameTest",
          "acidKeepsHurting",
          "aciddamagegametest.acidkeepshurting", "static" },
      { "com.faktocraft.gametest.machines.CanningMachineGameTest",
          "canningMachineEmptiesLavaBucketIntoTank",
          "canningmachinegametest.canningmachineemptieslavabucketintotank", "static" },
      { "com.faktocraft.gametest.machines.CanningMachineGameTest",
          "canningMachineFillsBucketFromTank",
          "canningmachinegametest.canningmachinefillsbucketfromtank", "static" },
      { "com.faktocraft.gametest.machines.CanningMachineGameTest",
          "canningMachineFillsGlassBottles",
          "canningmachinegametest.canningmachinefillsglassbottles", "static" },
      { "com.faktocraft.gametest.machines.CanningMachineGameTest",
          "canningMachineKeepsBucketWithHalfTank",
          "canningmachinegametest.canningmachinekeepsbucketwithhalftank", "static" },
      { "com.faktocraft.gametest.machines.CanningMachineGameTest",
          "canningMachineLeavesBottleWithoutWater",
          "canningmachinegametest.canningmachineleavesbottlewithoutwater", "static" },
      { "com.faktocraft.gametest.world.ChunkLoaderGameTest",
          "enableForcesAndDisableReleases",
          "chunkloadergametest.enableforcesanddisablereleases", "static" },
      { "com.faktocraft.gametest.world.ChunkLoaderGameTest",
          "managerEnforcesSlotLimit",
          "chunkloadergametest.managerenforcesslotlimit", "static" },
      { "com.faktocraft.gametest.world.ChunkLoaderGameTest",
          "starvedLoaderReleasesChunksButKeepsSlot",
          "chunkloadergametest.starvedloaderreleaseschunksbutkeepsslot", "static" },
      { "com.faktocraft.gametest.logistics.ConfigClipboardGameTest",
          "craftPipeConfigCopiesBetweenPipes",
          "configclipboardgametest.craftpipeconfigcopiesbetweenpipes", "static" },
      { "com.faktocraft.gametest.logistics.ConfigClipboardGameTest",
          "craftPipeSingleRecipeCopiesBetweenPipes",
          "configclipboardgametest.craftpipesinglerecipecopiesbetweenpipes", "static" },
      { "com.faktocraft.gametest.logistics.ConfigClipboardGameTest",
          "moduleConfigCopiesBetweenModules",
          "configclipboardgametest.moduleconfigcopiesbetweenmodules", "static" },
      { "com.faktocraft.gametest.logistics.ConfigClipboardGameTest",
          "recipePipeSingleRecipeCopiesBetweenPipes",
          "configclipboardgametest.recipepipesinglerecipecopiesbetweenpipes", "static" },
      { "com.faktocraft.gametest.fluids.EnderTankGameTest",
          "enderTankCodeChangeLeavesFluidInTheOldChannel",
          "endertankgametest.endertankcodechangeleavesfluidintheoldchannel", "static" },
      { "com.faktocraft.gametest.fluids.EnderTankGameTest",
          "enderTanksWithDifferentCodesStaySeparate",
          "endertankgametest.endertankswithdifferentcodesstayseparate", "static" },
      { "com.faktocraft.gametest.fluids.EnderTankGameTest",
          "enderTanksWithTheSameCodeShareFluid",
          "endertankgametest.endertankswiththesamecodesharefluid", "static" },
      { "com.faktocraft.gametest.fluids.EnderTankGameTest",
          "enderTankWithoutCodeRefusesFluid",
          "endertankgametest.endertankwithoutcoderefusesfluid", "static" },
      { "com.faktocraft.gametest.fluids.EnderTankGameTest",
          "stackedEnderTanksDoNotSettleIntoEachOther",
          "endertankgametest.stackedendertanksdonotsettleintoeachother", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "allGoldControl",
          "energynetworkgametest.allgoldcontrol", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "archTopFeedGoldFirst",
          "energynetworkgametest.archtopfeedgoldfirst", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "archTopFeedGoldLast",
          "energynetworkgametest.archtopfeedgoldlast", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "breakerInlineDeliversEnergy",
          "energynetworkgametest.breakerinlinedeliversenergy", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "breakerOffLeavesGeneratorFull",
          "energynetworkgametest.breakeroffleavesgeneratorfull", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "breakerPlacedVerticallyPicksAxis",
          "energynetworkgametest.breakerplacedverticallypicksaxis", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "breakerRoundTripStaysQuiet",
          "energynetworkgametest.breakerroundtripstaysquiet", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "breakerSideCableIsNotBurned",
          "energynetworkgametest.breakersidecableisnotburned", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "breakerToggleOffOnRecovers",
          "energynetworkgametest.breakertoggleoffonrecovers", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "breakerTopFeedDeliversEnergy",
          "energynetworkgametest.breakertopfeeddeliversenergy", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "deadEndWireFeedsLateMachine",
          "energynetworkgametest.deadendwirefeedslatemachine", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "generatorPriorityDrainsHighestFirst",
          "energynetworkgametest.generatorprioritydrainshighestfirst", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "geoGeneratorRestartHysteresis",
          "energynetworkgametest.geogeneratorrestarthysteresis", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "ghostClaimDoesNotSplitRun",
          "energynetworkgametest.ghostclaimdoesnotsplitrun", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "goldBridgeBetweenHvBuiltLinear",
          "energynetworkgametest.goldbridgebetweenhvbuiltlinear", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "goldBridgeBetweenHvPlacedLast",
          "energynetworkgametest.goldbridgebetweenhvplacedlast", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "goldBridgeBuiltFromTransformerSide",
          "energynetworkgametest.goldbridgebuiltfromtransformerside", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "hvLineMachinesLast",
          "energynetworkgametest.hvlinemachineslast", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "loadingDropsDuplicateClaims",
          "energynetworkgametest.loadingdropsduplicateclaims", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "loopSplitKeepsSingleNetwork",
          "energynetworkgametest.loopsplitkeepssinglenetwork", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "mixedArchMachinesLast",
          "energynetworkgametest.mixedarchmachineslast", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "mixedTierChainRespectsDemand",
          "energynetworkgametest.mixedtierchainrespectsdemand", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "mixedTiersFarSideFirst",
          "energynetworkgametest.mixedtiersfarsidefirst", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "mixedTiersSourceSideFirst",
          "energynetworkgametest.mixedtierssourcesidefirst", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "mixedTiersSurvivesSaveReload",
          "energynetworkgametest.mixedtierssurvivessavereload", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "orphanRunHealedByCablePlacement",
          "energynetworkgametest.orphanrunhealedbycableplacement", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "orphanRunHealedByNetRepair",
          "energynetworkgametest.orphanrunhealedbynetrepair", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "sideMachineFedDespiteOutputFaceOnTrunk",
          "energynetworkgametest.sidemachinefeddespiteoutputfaceontrunk", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "singleCableMachinesLast",
          "energynetworkgametest.singlecablemachineslast", "static" },
      { "com.faktocraft.gametest.energy.EnergyNetworkGameTest",
          "veryHighTransformerOnlyStepsDown",
          "energynetworkgametest.veryhightransformeronlystepsdown", "static" },
      { "com.faktocraft.gametest.logistics.ExtractorPipeGameTest",
          "extractorPipeBufferIsTheDockedCapacitor",
          "extractorpipegametest.extractorpipebufferisthedockedcapacitor", "static" },
      { "com.faktocraft.gametest.logistics.ExtractorPipeGameTest",
          "fluidExtractorPipeAnswersTheEnergyLookup",
          "extractorpipegametest.fluidextractorpipeanswerstheenergylookup", "static" },
      { "com.faktocraft.gametest.logistics.ExtractorPipeGameTest",
          "fluidExtractorPipeDraftsFromItsTank",
          "extractorpipegametest.fluidextractorpipedraftsfromitstank", "static" },
      { "com.faktocraft.gametest.logistics.ExtractorPipeGameTest",
          "fluidExtractorPipeIdlesWithoutPower",
          "extractorpipegametest.fluidextractorpipeidleswithoutpower", "static" },
      { "com.faktocraft.gametest.fluids.FluidMovementGameTest",
          "livingEntityMovesInCoolant",
          "fluidmovementgametest.livingentitymovesincoolant", "static" },
      { "com.faktocraft.gametest.fluids.FluidMovementGameTest",
          "livingEntityMovesInOil",
          "fluidmovementgametest.livingentitymovesinoil", "static" },
      { "com.faktocraft.gametest.fluids.FluidPipeGameTest",
          "closedValveIsolatesPipe",
          "fluidpipegametest.closedvalveisolatespipe", "static" },
      { "com.faktocraft.gametest.fluids.FluidPipeGameTest",
          "columnDrainsIntoTankBelow",
          "fluidpipegametest.columndrainsintotankbelow", "static" },
      { "com.faktocraft.gametest.fluids.FluidPipeGameTest",
          "junctionRespectsTierRate",
          "fluidpipegametest.junctionrespectstierrate", "static" },
      { "com.faktocraft.gametest.fluids.FluidPipeGameTest",
          "plateauDrainsIntoTank",
          "fluidpipegametest.plateaudrainsintotank", "static" },
      { "com.faktocraft.gametest.fluids.FluidPipeGameTest",
          "tailDrainsIntoTankEast",
          "fluidpipegametest.taildrainsintotankeast", "static" },
      { "com.faktocraft.gametest.fluids.FluidPipeGameTest",
          "tailDrainsIntoTankWest",
          "fluidpipegametest.taildrainsintotankwest", "static" },
      { "com.faktocraft.gametest.fluids.FluidPipeGameTest",
          "valveReleaseStreamStaysVisible",
          "fluidpipegametest.valvereleasestreamstaysvisible", "static" },
      { "com.faktocraft.gametest.world.ForesterGameTest",
          "foresterAreaBlocksFancyOakAndForeignSaplings",
          "forestergametest.foresterareablocksfancyoakandforeignsaplings", "static" },
      { "com.faktocraft.gametest.world.ForesterGameTest",
          "foresterFellsTreeAndReplants",
          "forestergametest.foresterfellstreeandreplants", "static" },
      { "com.faktocraft.gametest.world.ForesterGameTest",
          "foresterFrameFollowsSaplingHeights",
          "forestergametest.foresterframefollowssaplingheights", "static" },
      { "com.faktocraft.gametest.world.ForesterGameTest",
          "foresterHarvestsEveryLeaf",
          "forestergametest.foresterharvestseveryleaf", "static" },
      { "com.faktocraft.gametest.world.ForesterGameTest",
          "foresterKeepsFertilizingUntilTheTreeGrows",
          "forestergametest.foresterkeepsfertilizinguntilthetreegrows", "static" },
      { "com.faktocraft.gametest.world.ForesterGameTest",
          "foresterTapsRubberWhenAskedAndFellsOtherwise",
          "forestergametest.forestertapsrubberwhenaskedandfellsotherwise", "static" },
      { "com.faktocraft.gametest.world.HoleDrillGameTest",
          "cableFitsInsideDrilledBlockAndPopsOutOnBreak",
          "holedrillgametest.cablefitsinsidedrilledblockandpopsoutonbreak", "static" },
      { "com.faktocraft.gametest.world.HoleDrillGameTest",
          "drillBoresBlock",
          "holedrillgametest.drillboresblock", "static" },
      { "com.faktocraft.gametest.world.HoleDrillGameTest",
          "drilledBlockHoldsPipesWithoutBlockEntity",
          "holedrillgametest.drilledblockholdspipeswithoutblockentity", "static" },
      { "com.faktocraft.gametest.world.HoleDrillGameTest",
          "drilledBlockLetsLightIn",
          "holedrillgametest.drilledblockletslightin", "static" },
      { "com.faktocraft.gametest.world.HoleDrillGameTest",
          "drillOnOpenSideBoresTheOppositeSide",
          "holedrillgametest.drillonopensideborestheoppositeside", "static" },
      { "com.faktocraft.gametest.blocks.IridiumOreGameTest",
          "deepslateIridiumOreEmitsFaintLight",
          "iridiumoregametest.deepslateiridiumoreemitsfaintlight", "static" },
      { "com.faktocraft.gametest.blocks.IridiumOreGameTest",
          "iridiumOreEmitsFaintLight",
          "iridiumoregametest.iridiumoreemitsfaintlight", "static" },
      { "com.faktocraft.gametest.legacy.LegacyFixtureGameTest",
          "buildLegacyFixture",
          "legacyfixturegametest.buildlegacyfixture", "instance" },
      { "com.faktocraft.gametest.legacy.LegacySaveGameTest",
          "legacySaveNbtParity",
          "legacysavegametest.legacysavenbtparity", "instance" },
      { "com.faktocraft.gametest.legacy.LegacySaveGameTest",
          "legacySaveWorldParity",
          "legacysavegametest.legacysaveworldparity", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "cancelMidChainRecoversIntermediates",
          "logisticschaingametest.cancelmidchainrecoversintermediates", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "deliveriesStreamWhileStillProducing",
          "logisticschaingametest.deliveriesstreamwhilestillproducing", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "downstreamStepStartsBeforeUpstreamFinishes",
          "logisticschaingametest.downstreamstepstartsbeforeupstreamfinishes", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "electricAndVanillaFurnacesShareOneRequest",
          "logisticschaingametest.electricandvanillafurnacesshareonerequest", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "fourBenchChainWithSurplusReturnsLeftovers",
          "logisticschaingametest.fourbenchchainwithsurplusreturnsleftovers", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "furnacePairSmeltsSixteenWithStreamingOutput",
          "logisticschaingametest.furnacepairsmeltssixteenwithstreamingoutput", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "largeCraftSplitsAcrossTwoTables",
          "logisticschaingametest.largecraftsplitsacrosstwotables", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "longChainStressBuildsSixtyFourCraftingTables",
          "logisticschaingametest.longchainstressbuildssixtyfourcraftingtables", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "machineRemovedMidJobFailsAndFreesTheRequest",
          "logisticschaingametest.machineremovedmidjobfailsandfreestherequest", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "manyConcurrentRequestsAllComplete",
          "logisticschaingametest.manyconcurrentrequestsallcomplete", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "mixedRequestsQueueOnSharedStations",
          "logisticschaingametest.mixedrequestsqueueonsharedstations", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "modCrusherCraftsThroughRecipePipe",
          "logisticschaingametest.modcrushercraftsthroughrecipepipe", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "requestBeyondStockFailsCleanly",
          "logisticschaingametest.requestbeyondstockfailscleanly", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "sharedPipesSplitTheRequest",
          "logisticschaingametest.sharedpipessplittherequest", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "sixStageChainMixesMachinesAndBenches",
          "logisticschaingametest.sixstagechainmixesmachinesandbenches", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "sixStageChainTwiceWithTwoFurnaces",
          "logisticschaingametest.sixstagechaintwicewithtwofurnaces", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "stockRequestDeliversAThousandItems",
          "logisticschaingametest.stockrequestdeliversathousanditems", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "unsharedPipeKeepsTheWholeRequest",
          "logisticschaingametest.unsharedpipekeepsthewholerequest", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsChainGameTest",
          "vanillaFurnaceWithFuelKeptStocked",
          "logisticschaingametest.vanillafurnacewithfuelkeptstocked", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "cancelFromAnotherOriginIsRefused",
          "logisticscoveragegametest.cancelfromanotheroriginisrefused", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "chassisMk2UsesItsThirdModuleSlot",
          "logisticscoveragegametest.chassismk2usesitsthirdmoduleslot", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "chestFullOfDirtStillLetsPlanksThrough",
          "logisticscoveragegametest.chestfullofdirtstillletsplanksthrough", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "collectorLinesFilterGroundItems",
          "logisticscoveragegametest.collectorlinesfiltergrounditems", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "eightBenchesShareOneRequest",
          "logisticscoveragegametest.eightbenchesshareonerequest", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "energyIsChargedPerMovedItem",
          "logisticscoveragegametest.energyischargedpermoveditem", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "extractorTagLineFiltersItems",
          "logisticscoveragegametest.extractortaglinefiltersitems", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "fullSinkFallsBackToTheNextOne",
          "logisticscoveragegametest.fullsinkfallsbacktothenextone", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "fullTableBouncesDeliveriesUntilThereIsRoom",
          "logisticscoveragegametest.fulltablebouncesdeliveriesuntilthereisroom", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "furnaceKeepsPreexistingOutput",
          "logisticscoveragegametest.furnacekeepspreexistingoutput", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "historyKeepsOnlyTheLastHundred",
          "logisticscoveragegametest.historykeepsonlythelasthundred", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "hugeCraftFailsAsTooComplex",
          "logisticscoveragegametest.hugecraftfailsastoocomplex", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "invalidBindingAndMissingMachineAreReported",
          "logisticscoveragegametest.invalidbindingandmissingmachinearereported", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "ledgerSurvivesSaveAndLoadMidJob",
          "logisticscoveragegametest.ledgersurvivessaveandloadmidjob", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "providerExcludeFlagHidesItems",
          "logisticscoveragegametest.providerexcludeflaghidesitems", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "providerMinReserveIsKept",
          "logisticscoveragegametest.providerminreserveiskept", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "providerPriorityWinsOverDistance",
          "logisticscoveragegametest.providerprioritywinsoverdistance", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "recipeCycleIsDetected",
          "logisticscoveragegametest.recipecycleisdetected", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "recipePipeRemovedMidJobFails",
          "logisticscoveragegametest.recipepiperemovedmidjobfails", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "recipePipeWithTwoRecipesServesBoth",
          "logisticscoveragegametest.recipepipewithtworecipesservesboth", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "removingTheCoreDropsEverythingInCustody",
          "logisticscoveragegametest.removingthecoredropseverythingincustody", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "requestQuantityIsCappedAtFourThousandNinetySix",
          "logisticscoveragegametest.requestquantityiscappedatfourthousandninetysix", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "requestWithNbtVariantsInStock",
          "logisticscoveragegametest.requestwithnbtvariantsinstock", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "reservedStockIsNotOfferedTwice",
          "logisticscoveragegametest.reservedstockisnotofferedtwice", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "sameBenchServesTwoStepsOfOneRequest",
          "logisticscoveragegametest.samebenchservestwostepsofonerequest", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "secondCoreOnTheNetworkRefusesRequests",
          "logisticscoveragegametest.secondcoreonthenetworkrefusesrequests", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "singleSlotOutputGrowsBeyondSixtyFour",
          "logisticscoveragegametest.singleslotoutputgrowsbeyondsixtyfour", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "sinkNearestToTheCoreWinsTies",
          "logisticscoveragegametest.sinknearesttothecorewinsties", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "sinkTagAndNamespaceLinesRoute",
          "logisticscoveragegametest.sinktagandnamespacelinesroute", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "stalledMachineTimesOutAndReturnsInputs",
          "logisticscoveragegametest.stalledmachinetimesoutandreturnsinputs", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "supplierCraftsWhenAllowed",
          "logisticscoveragegametest.suppliercraftswhenallowed", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "supplierWithoutCraftsOnlyUsesStock",
          "logisticscoveragegametest.supplierwithoutcraftsonlyusesstock", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "throughputUpgradeSpeedsUpTheExtractor",
          "logisticscoveragegametest.throughputupgradespeedsuptheextractor", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "twoTablesShareOneBench",
          "logisticscoveragegametest.twotablesshareonebench", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsCoverageGameTest",
          "unpoweredCorePausesAndResumes",
          "logisticscoveragegametest.unpoweredcorepausesandresumes", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "assemblyLeftoverDrainsToSink",
          "logisticsgametest.assemblyleftoverdrainstosink", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "assemblyTableRunsOnLowVoltage",
          "logisticsgametest.assemblytablerunsonlowvoltage", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "assemblyTableShowsAndSoundsWhileCrafting",
          "logisticsgametest.assemblytableshowsandsoundswhilecrafting", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "blockedCraftReportsRootCause",
          "logisticsgametest.blockedcraftreportsrootcause", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "cancelRequestReturnsItems",
          "logisticsgametest.cancelrequestreturnsitems", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "chassisExtractorSortsBySink",
          "logisticsgametest.chassisextractorsortsbysink", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "craftPipeAcceptsEquivalents",
          "logisticsgametest.craftpipeacceptsequivalents", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "craftPipeMachineMode",
          "logisticsgametest.craftpipemachinemode", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "craftPipeSlotBinding",
          "logisticsgametest.craftpipeslotbinding", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "craftPipeStrictRefusesEquivalents",
          "logisticsgametest.craftpipestrictrefusesequivalents", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "flexibleIngredientBacktracksToCraftableVariant",
          "logisticsgametest.flexibleingredientbacktrackstocraftablevariant", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "fuelingStationFillsAndTheNetworkCollects",
          "logisticsgametest.fuelingstationfillsandthenetworkcollects", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "legacyEmptyTreeProviderStillStocks",
          "logisticsgametest.legacyemptytreeproviderstillstocks", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "machineRecipeTransformsInPlace",
          "logisticsgametest.machinerecipetransformsinplace", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "modulesStackInPacksButOnePerSlot",
          "logisticsgametest.modulesstackinpacksbutoneperslot", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "partialStockSplitsTasks",
          "logisticsgametest.partialstocksplitstasks", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "pipeDoesNotDockToTheMachineFront",
          "logisticsgametest.pipedoesnotdocktothemachinefront", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "providerAddedAtRuntimeIsConsulted",
          "logisticsgametest.provideraddedatruntimeisconsulted", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "requestKeepsItemData",
          "logisticsgametest.requestkeepsitemdata", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "requestTableBenchCraft",
          "logisticsgametest.requesttablebenchcraft", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "requestTableTurnsWithTheWrench",
          "logisticsgametest.requesttableturnswiththewrench", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "requestTellsDataVariantsApart",
          "logisticsgametest.requesttellsdatavariantsapart", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "sinkPriorityChangeRedirects",
          "logisticsgametest.sinkprioritychangeredirects", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "supplierCreatesSystemTask",
          "logisticsgametest.suppliercreatessystemtask", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "tableAutoExtractDrainsDeposit",
          "logisticsgametest.tableautoextractdrainsdeposit", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "toolboxTakesTheFieldTools",
          "logisticsgametest.toolboxtakesthefieldtools", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "treeCategoryOverrideResolves",
          "logisticsgametest.treecategoryoverrideresolves", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "treeExtractorPullsOnlyMarkedItems",
          "logisticsgametest.treeextractorpullsonlymarkeditems", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "treeSinkRoutesByOverrides",
          "logisticsgametest.treesinkroutesbyoverrides", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "treeSupplierKeepsTargetStock",
          "logisticsgametest.treesupplierkeepstargetstock", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "twoRequestsShareOneStation",
          "logisticsgametest.tworequestsshareonestation", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsGameTest",
          "twoStationsRunInParallel",
          "logisticsgametest.twostationsruninparallel", "instance" },
      { "com.faktocraft.gametest.logistics.LogisticsPipesGameTest",
          "collectorModuleShipsGroundItemsToTheSink",
          "logisticspipesgametest.collectormoduleshipsgrounditemstothesink", "static" },
      { "com.faktocraft.gametest.logistics.LogisticsPipesGameTest",
          "disposalModuleSwallowsWhatNoSinkTakes",
          "logisticspipesgametest.disposalmoduleswallowswhatnosinktakes", "static" },
      { "com.faktocraft.gametest.logistics.LogisticsPipesGameTest",
          "ejectorModuleDropsWhatNoSinkTakes",
          "logisticspipesgametest.ejectormoduledropswhatnosinktakes", "static" },
      { "com.faktocraft.gametest.logistics.LogisticsPipesGameTest",
          "goldPipeShortensTheTrip",
          "logisticspipesgametest.goldpipeshortensthetrip", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "fuelingStationRefillsCoolantCell",
          "nuclearreactorgametest.fuelingstationrefillscoolantcell", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorCasingBreakDropsCasingAndContents",
          "nuclearreactorgametest.reactorcasingbreakdropscasingandcontents", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorCellsSpendCoolantAndStayInPlace",
          "nuclearreactorgametest.reactorcellsspendcoolantandstayinplace", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorCoreBreakKeepsPlacedBlock",
          "nuclearreactorgametest.reactorcorebreakkeepsplacedblock", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorCorePlacedLastBySetBlockTicks",
          "nuclearreactorgametest.reactorcoreplacedlastbysetblockticks", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorCubeFormsWhenCasingPlacedLast",
          "nuclearreactorgametest.reactorcubeformswhencasingplacedlast", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorCubeFormsWhenReactorPlacedLast",
          "nuclearreactorgametest.reactorcubeformswhenreactorplacedlast", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorCubeNeedsAllCasings",
          "nuclearreactorgametest.reactorcubeneedsallcasings", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorCubePlacementAcceptedCompletingCube",
          "nuclearreactorgametest.reactorcubeplacementacceptedcompletingcube", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorCubePlacementRefusedWithoutCube",
          "nuclearreactorgametest.reactorcubeplacementrefusedwithoutcube", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorCubeRevertsWhenPartBroken",
          "nuclearreactorgametest.reactorcuberevertswhenpartbroken", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorHeatSettlesUnderCooling",
          "nuclearreactorgametest.reactorheatsettlesundercooling", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorHonoursRedstoneMode",
          "nuclearreactorgametest.reactorhonoursredstonemode", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorMeltsDownWhenOverheated",
          "nuclearreactorgametest.reactormeltsdownwhenoverheated", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorNeighbourRodsExciteEachOther",
          "nuclearreactorgametest.reactorneighbourrodsexciteeachother", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorOutputFollowsHeat",
          "nuclearreactorgametest.reactoroutputfollowsheat", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorPlacedBlockBreakDropsReactor",
          "nuclearreactorgametest.reactorplacedblockbreakdropsreactor", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorReflectorBoostsAndHeats",
          "nuclearreactorgametest.reactorreflectorboostsandheats", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorReformedWithDifferentRoleHasWorkingCore",
          "nuclearreactorgametest.reactorreformedwithdifferentrolehasworkingcore", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorRunsOnFuelRodAndWater",
          "nuclearreactorgametest.reactorrunsonfuelrodandwater", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorSidesCarryPowerAndWater",
          "nuclearreactorgametest.reactorsidescarrypowerandwater", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorSlowsDownWhenBufferFull",
          "nuclearreactorgametest.reactorslowsdownwhenbufferfull", "static" },
      { "com.faktocraft.gametest.nuclear.NuclearReactorGameTest",
          "reactorSpendsRodIntoDepleted",
          "nuclearreactorgametest.reactorspendsrodintodepleted", "static" },
      { "com.faktocraft.gametest.nuclear.NukeGameTest",
          "decontaminatorWipesFalloutNearby",
          "nukegametest.decontaminatorwipesfalloutnearby", "static" },
      { "com.faktocraft.gametest.nuclear.NukeGameTest",
          "nukeBlastSurvivesSaveAndLoad",
          "nukegametest.nukeblastsurvivessaveandload", "static" },
      { "com.faktocraft.gametest.nuclear.NukeGameTest",
          "nukeDisabledRefusesToPrime",
          "nukegametest.nukedisabledrefusestoprime", "static" },
      { "com.faktocraft.gametest.nuclear.NukeGameTest",
          "nukeVaporisesSoftBlocksAndSparesObsidian",
          "nukegametest.nukevaporisessoftblocksandsparesobsidian", "static" },
      { "com.faktocraft.gametest.fluids.PumpGameTest",
          "pumpDeepShaft",
          "pumpgametest.pumpdeepshaft", "static" },
      { "com.faktocraft.gametest.fluids.PumpGameTest",
          "pumpDeepShaftStaleTube",
          "pumpgametest.pumpdeepshaftstaletube", "static" },
      { "com.faktocraft.gametest.fluids.PumpGameTest",
          "pumpHandsTheBucketToTheNeighbour",
          "pumpgametest.pumphandsthebuckettotheneighbour", "static" },
      { "com.faktocraft.gametest.fluids.PumpGameTest",
          "pumpRecoversWhenShaftIsUnblocked",
          "pumpgametest.pumprecoverswhenshaftisunblocked", "static" },
      { "com.faktocraft.gametest.fluids.PumpGameTest",
          "pumpResumesAfterReload",
          "pumpgametest.pumpresumesafterreload", "static" },
      { "com.faktocraft.gametest.world.QuarryGameTest",
          "breakingQuarryRemovesFrame",
          "quarrygametest.breakingquarryremovesframe", "static" },
      { "com.faktocraft.gametest.world.QuarryGameTest",
          "incompleteLandmarksReportInvalidArea",
          "quarrygametest.incompletelandmarksreportinvalidarea", "static" },
      { "com.faktocraft.gametest.world.QuarryGameTest",
          "landmarkAreaMinesOreButSparesSpawner",
          "quarrygametest.landmarkareaminesorebutsparesspawner", "static" },
      { "com.faktocraft.gametest.world.QuarryGameTest",
          "landmarkAreaMinesUntaggedBlockButSparesChestAndModBlock",
          "quarrygametest.landmarkareaminesuntaggedblockbutspareschestandmodblock", "static" },
      { "com.faktocraft.gametest.world.QuarryGameTest",
          "quarryBesideEdgeResolvesSameArea",
          "quarrygametest.quarrybesideedgeresolvessamearea", "static" },
      { "com.faktocraft.gametest.world.QuarryGameTest",
          "quarryNextToArmEndResolvesSameArea",
          "quarrygametest.quarrynexttoarmendresolvessamearea", "static" },
      { "com.faktocraft.gametest.nuclear.RadiationGameTest",
          "geigerReadingSeesChestAndPocket",
          "radiationgametest.geigerreadingseeschestandpocket", "static" },
      { "com.faktocraft.gametest.nuclear.RadiationGameTest",
          "highDoseHurtsHardButNeverOneShots",
          "radiationgametest.highdosehurtshardbutneveroneshots", "static" },
      { "com.faktocraft.gametest.nuclear.RadiationGameTest",
          "lowDoseHurtsOnlyAfterExposure",
          "radiationgametest.lowdosehurtsonlyafterexposure", "static" },
      { "com.faktocraft.gametest.nuclear.RadiationGameTest",
          "radiationBlockedByLead",
          "radiationgametest.radiationblockedbylead", "static" },
      { "com.faktocraft.gametest.nuclear.RadiationGameTest",
          "radiationDoseFallsWithDistanceAndShielding",
          "radiationgametest.radiationdosefallswithdistanceandshielding", "static" },
      { "com.faktocraft.gametest.nuclear.RadiationGameTest",
          "radiationExposureKeepsDecayingAfterRejoin",
          "radiationgametest.radiationexposurekeepsdecayingafterrejoin", "static" },
      { "com.faktocraft.gametest.nuclear.RadiationGameTest",
          "radiationExposureRecovers",
          "radiationgametest.radiationexposurerecovers", "static" },
      { "com.faktocraft.gametest.nuclear.RadiationGameTest",
          "radiationHitsNearbyCreature",
          "radiationgametest.radiationhitsnearbycreature", "static" },
      { "com.faktocraft.gametest.nuclear.RadiationGameTest",
          "radiationSparesHazmatSuit",
          "radiationgametest.radiationspareshazmatsuit", "static" },
      { "com.faktocraft.gametest.nuclear.RadiationGameTest",
          "uraniumOreVeinRadiatesFaintly",
          "radiationgametest.uraniumoreveinradiatesfaintly", "static" },
      { "com.faktocraft.gametest.logistics.RecipePipeBatchGameTest",
          "brewingStandBatchesFourPotions",
          "recipepipebatchgametest.brewingstandbatchesfourpotions", "instance" },
      { "com.faktocraft.gametest.logistics.RecipePipeBatchGameTest",
          "brewingStandBatchesSevenPotions",
          "recipepipebatchgametest.brewingstandbatchessevenpotions", "instance" },
      { "com.faktocraft.gametest.logistics.RecipePipeBatchGameTest",
          "brewingStandLeftoverBottlesReturnToStock",
          "recipepipebatchgametest.brewingstandleftoverbottlesreturntostock", "instance" },
      { "com.faktocraft.gametest.logistics.RecipePipeBatchGameTest",
          "legacyRecipeStillRunsOnTheFuelingStation",
          "recipepipebatchgametest.legacyrecipestillrunsonthefuelingstation", "instance" },
      { "com.faktocraft.gametest.machines.RecyclerGameTest",
          "recyclerTurnsNuclearWasteIntoPlentyOfScrap",
          "recyclergametest.recyclerturnsnuclearwasteintoplentyofscrap", "static" },
      { "com.faktocraft.gametest.world.ReinforcedStoneDoorGameTest",
          "reinforcedStoneDoorOpensByRedstoneOnly",
          "reinforcedstonedoorgametest.reinforcedstonedooropensbyredstoneonly", "static" },
      { "com.faktocraft.gametest.world.ReinforcedStoneDoorGameTest",
          "reinforcedStoneDoorShieldsRadiationWhileClosed",
          "reinforcedstonedoorgametest.reinforcedstonedoorshieldsradiationwhileclosed", "static" },
      { "com.faktocraft.gametest.world.RubberTreeGameTest",
          "rubberTreeAlwaysHasResinSpot",
          "rubbertreegametest.rubbertreealwayshasresinspot", "static" },
      { "com.faktocraft.gametest.world.ScanChannelGameTest",
          "geoScannerAreaIsRound",
          "scanchannelgametest.geoscannerareaisround", "static" },
      { "com.faktocraft.gametest.world.ScanChannelGameTest",
          "scanChannelDefaultPassword",
          "scanchannelgametest.scanchanneldefaultpassword", "static" },
      { "com.faktocraft.gametest.world.ScanChannelGameTest",
          "scanChannelSharedByPassword",
          "scanchannelgametest.scanchannelsharedbypassword", "static" },
      { "com.faktocraft.gametest.world.ScanChannelGameTest",
          "scanPacketsSurviveLargeScans",
          "scanchannelgametest.scanpacketssurvivelargescans", "static" },
      { "com.faktocraft.gametest.machines.ShiftClickGameTest",
          "assemblyTableKeepsCapacitorsOutOfTheIngredients",
          "shiftclickgametest.assemblytablekeepscapacitorsoutoftheingredients", "static" },
      { "com.faktocraft.gametest.machines.ShiftClickGameTest",
          "shiftClickPrefersTheSideBays",
          "shiftclickgametest.shiftclickprefersthesidebays", "static" },
      { "com.faktocraft.gametest.logistics.SlotLayoutGameTest",
          "slotYCanBeMovedByReflection",
          "slotlayoutgametest.slotycanbemovedbyreflection", "static" },
      { "com.faktocraft.gametest.machines.StatusMonitorGameTest",
          "statusMonitorCarriesJadeFluidDataForTank",
          "statusmonitorgametest.statusmonitorcarriesjadefluiddatafortank", "static" },
      { "com.faktocraft.gametest.machines.StatusMonitorGameTest",
          "statusMonitorListsChestContentsAndJoinsNeighbours",
          "statusmonitorgametest.statusmonitorlistschestcontentsandjoinsneighbours", "static" },
      { "com.faktocraft.gametest.machines.StatusMonitorGameTest",
          "statusMonitorPlacesSixPartsAndBreaksAsOne",
          "statusmonitorgametest.statusmonitorplacessixpartsandbreaksasone", "static" },
      { "com.faktocraft.gametest.machines.StatusMonitorGameTest",
          "statusMonitorShowsMachineEnergyAndNoticesRemoval",
          "statusmonitorgametest.statusmonitorshowsmachineenergyandnoticesremoval", "static" },
      { "com.faktocraft.gametest.world.TeleportAnchorGameTest",
          "anchorKeepsEnergyAboveDefaultBufferAfterReload",
          "teleportanchorgametest.anchorkeepsenergyabovedefaultbufferafterreload", "static" },
      { "com.faktocraft.gametest.world.TeleportAnchorGameTest",
          "basicAnchorStaysInItsDimension",
          "teleportanchorgametest.basicanchorstaysinitsdimension", "static" },
      { "com.faktocraft.gametest.world.TeleportAnchorGameTest",
          "dimensionalAnchorLinksAcrossDimensions",
          "teleportanchorgametest.dimensionalanchorlinksacrossdimensions", "static" },
      { "com.faktocraft.gametest.world.TeleportAnchorGameTest",
          "dimensionalAnchorPreloadsDestinationArea",
          "teleportanchorgametest.dimensionalanchorpreloadsdestinationarea", "static" },
      { "com.faktocraft.gametest.tools.ToolSpeedGameTest",
          "chainsawDigsStoneByHand",
          "toolspeedgametest.chainsawdigsstonebyhand", "static" },
      { "com.faktocraft.gametest.tools.ToolSpeedGameTest",
          "chainsawMatchesIronAxe",
          "toolspeedgametest.chainsawmatchesironaxe", "static" },
      { "com.faktocraft.gametest.tools.ToolSpeedGameTest",
          "diamondChainsawFivePercentOverDiamondAxe",
          "toolspeedgametest.diamondchainsawfivepercentoverdiamondaxe", "static" },
      { "com.faktocraft.gametest.tools.ToolSpeedGameTest",
          "diamondDrillFivePercentOverDiamondPickaxe",
          "toolspeedgametest.diamonddrillfivepercentoverdiamondpickaxe", "static" },
      { "com.faktocraft.gametest.tools.ToolSpeedGameTest",
          "dischargedDrillDigsByHand",
          "toolspeedgametest.dischargeddrilldigsbyhand", "static" },
      { "com.faktocraft.gametest.tools.ToolSpeedGameTest",
          "iridiumChainsawTwentyPercentOverNetheriteAxe",
          "toolspeedgametest.iridiumchainsawtwentypercentovernetheriteaxe", "static" },
      { "com.faktocraft.gametest.tools.ToolSpeedGameTest",
          "iridiumDrillTwentyPercentOverNetheritePickaxe",
          "toolspeedgametest.iridiumdrilltwentypercentovernetheritepickaxe", "static" },
      { "com.faktocraft.gametest.tools.ToolSpeedGameTest",
          "ironDrillMatchesIronPickaxe",
          "toolspeedgametest.irondrillmatchesironpickaxe", "static" },
      { "com.faktocraft.gametest.energy.TransformerLossGameTest",
          "fillingUpNeverOverflows",
          "transformerlossgametest.fillingupneveroverflows", "static" },
      { "com.faktocraft.gametest.energy.TransformerLossGameTest",
          "simulateDoesNotMoveTheCarry",
          "transformerlossgametest.simulatedoesnotmovethecarry", "static" },
      { "com.faktocraft.gametest.energy.TransformerLossGameTest",
          "smallFlowsCarryTheRemainder",
          "transformerlossgametest.smallflowscarrytheremainder", "static" },
      { "com.faktocraft.gametest.energy.TransformerLossGameTest",
          "stepDownUsesItsOwnShare",
          "transformerlossgametest.stepdownusesitsownshare", "static" },
      { "com.faktocraft.gametest.energy.TransformerLossGameTest",
          "stepUpLosesConfiguredShare",
          "transformerlossgametest.stepuplosesconfiguredshare", "static" },
      { "com.faktocraft.gametest.machines.UraniumCentrifugeGameTest",
          "uraniumCentrifugeOnlyExposesItemsBelow",
          "uraniumcentrifugegametest.uraniumcentrifugeonlyexposesitemsbelow", "static" },
      { "com.faktocraft.gametest.machines.UraniumCentrifugeGameTest",
          "uraniumCentrifugeProducesDepletedDust",
          "uraniumcentrifugegametest.uraniumcentrifugeproducesdepleteddust", "static" },
      { "com.faktocraft.gametest.machines.UraniumCentrifugeGameTest",
          "uraniumCentrifugeRejectsOtherDust",
          "uraniumcentrifugegametest.uraniumcentrifugerejectsotherdust", "static" },
      { "com.faktocraft.gametest.machines.UraniumCentrifugeGameTest",
          "uraniumCentrifugeReprocessesDepletedRod",
          "uraniumcentrifugegametest.uraniumcentrifugereprocessesdepletedrod", "static" },
      { "com.faktocraft.gametest.tools.VeinMiningGameTest",
          "glowstoneCountsAsVein",
          "veinmininggametest.glowstonecountsasvein", "static" },
      { "com.faktocraft.gametest.tools.VeinMiningGameTest",
          "oreVeinGroupsDeepslateVariantAndSkipsOtherOres",
          "veinmininggametest.oreveingroupsdeepslatevariantandskipsotherores", "static" },
      { "com.faktocraft.gametest.tools.VeinMiningGameTest",
          "treeVeinOnlyFollowsTheSameLog",
          "veinmininggametest.treeveinonlyfollowsthesamelog", "static" },
      { "com.faktocraft.gametest.tools.VeinMiningGameTest",
          "veinStopsAtTheConfiguredLimit",
          "veinmininggametest.veinstopsattheconfiguredlimit", "static" },
  };
}
